services:
  app:
    build: .
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    tty: true
    env_file:
      - .env.docker
    depends_on:
      - db
  db:
    image: postgres:14.11-bullseye
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - .env.docker
    ports:
      - '5432:5432'
  redis:
    image: redis:latest
    ports:
      - 6379
  sidekiq:
    build: .
    command: bundle exec sidekiq
    env_file:
      - .env.docker
    depends_on:
      - redis
      - db
